spinx = ["MMM",
         'AOS',
         'ABT',
        #  'ABBV',
        #  'ACN',
        #  'ATVI',
        #  'ADM',
        #  'ADBE',
        #  'ADP',
        #  'AAP',
        #  'AES',
        #  'AFL',
        #  'A',
        #  'APD',
        #  'AKAM',
        #  'ALK',
        #  'ALB',
        #  'ARE',
        #  'ALGN',
        #  'ALLE',
        #  'LNT',
        #  'ALL',
        #  'GOOGL',
        #  'GOOG',
        #  'MO',
        #  'AMZN',
        #  'AMCR',
        #  'AEE',
        #  'AEE',
        #  'AAL',
        #  'AEP',
        #  'AXP',
         ]
